name: 'asset_correlation'
version: '1.0.0'

profile: 'asset_correlation'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  asset_correlation:
    staging:
      +materialized: view
