asset_correlation:
  outputs:
    dev:
      aws_profile_name: default
      database: awsdatacatalog
      region_name: ap-southeast-1
      s3_data_dir: "{{ env_var('S3_ATHENA_DATA_DIR') }}"
      s3_staging_dir: "{{ env_var('S3_ATHENA_STAGING_DIR') }}"
      schema: "{{ env_var('DBT_TARGET_SCHEMA', 'asset_correlation') }}"
      threads: 4
      type: athena
      work_group: primary
  target: dev
